FROM ubuntu:20.04

ARG USER_ID
ARG GROUP_ID

# Colors and italics for tmux
COPY xterm-256color-italic.terminfo /root
RUN tic /root/xterm-256color-italic.terminfo
ENV TERM=xterm-256color-italic

ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install \
        software-properties-common \
        build-essential \
        dialog \
        apt-utils \
        cmake \
        make \
        git \
        vim \
        curl \
        fzf \
        wget \
        tmux \
        tzdata \
        sudo \
        tree \
        python3 \
        python3-pip \
        python3-venv \
        ripgrep \
        nodejs \
        npm \
        fd-find \
        zsh

## neovim install
RUN add-apt-repository -y ppa:neovim-ppa/unstable && \ 
    apt-get update && \ 
    apt-get install -y neovim

RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user
USER user

# Build with the following command
# docker build -t myimage --build-arg USER_ID=$(id -u) \
#   --build-arg GROUP_ID=$(id -g) .

# change shell to zsh
CMD ["chsh",  "-s", "/usr/bin/zsh"]
